INSERT INTO defaultdb.users (id, first_name, last_name, email) VALUES (1, 'Paul', 'Harrohide', 'paul@gmail.com');
INSERT INTO defaultdb.users (id, first_name, last_name, email) VALUES (2, 'Harry', 'Covert', 'harry@gmail.com');
INSERT INTO defaultdb.programmes (id_programme, nom_programme) VALUES (1, 'Expert');
INSERT INTO defaultdb.programmes (id_programme, nom_programme) VALUES (2, 'Novice');
INSERT INTO defaultdb.seances (id_seance, id_programme) VALUES (1, 1);
INSERT INTO defaultdb.seances (id_seance, id_programme) VALUES (2, 1);
INSERT INTO defaultdb.seances (id_seance, id_programme) VALUES (3, 2);
INSERT INTO defaultdb.exercices (id_exercice, nom, serie, repetition, pourcentage_rm, id_seance) VALUES (1, 'Squat', 4, 5, 80, 1);
INSERT INTO defaultdb.exercices (id_exercice, nom, serie, repetition, pourcentage_rm, id_seance) VALUES (2, 'Terre', 4, 5, 80, 1);
INSERT INTO defaultdb.exercices (id_exercice, nom, serie, repetition, pourcentage_rm, id_seance) VALUES (3, 'Bench', 4, 5, 80, 2);
INSERT INTO defaultdb.exercices (id_exercice, nom, serie, repetition, pourcentage_rm, id_seance) VALUES (4, 'curl biceps', 4, 10, 75, 3);